# Generated by Django 6.1 on 2026-08-18 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('ai', 'AI'), ('integration', 'Integration'), ('api', 'API')], max_length=20)),
                ('actor_id', models.CharField(blank=True, help_text="Identifier of the actor within its actor_type namespace (e.g. a user's UUID as a string, an integration's slug, an AI agent's identifier). Null for actor_type=SYSTEM when there is no meaningful sub-identifier.", max_length=255, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('login', 'Login'), ('sync', 'Sync'), ('import', 'Import'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('execute', 'Execute'), ('other', 'Other')], max_length=20)),
                ('resource_type', models.CharField(help_text='Dotted reference to the affected model, e.g. "products.Product".', max_length=255)),
                ('resource_id', models.CharField(help_text='Stringified primary key of the affected resource.', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Lightweight structured diff, e.g. {"field": {"old": ..., "new": ...}}. Never store secrets. Keep small — this is a change summary, not a full snapshot.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional non-secret context for this event.')),
                ('correlation_id', models.UUIDField(blank=True, help_text='Groups events belonging to the same multi-step workflow.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event was recorded (UTC). Immutable.')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_by_resource'), models.Index(fields=['actor_type', 'actor_id'], name='audit_by_actor'), models.Index(fields=['action', 'created_at'], name='audit_by_action_time'), models.Index(fields=['created_at'], name='audit_by_created_at'), models.Index(fields=['correlation_id'], name='audit_by_correlation')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['user', 'system', 'ai', 'integration', 'api'])), name='audit_event_valid_actor_type'), models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'delete', 'restore', 'login', 'sync', 'import', 'export', 'approve', 'reject', 'execute', 'other'])), name='audit_event_valid_action')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('key', models.CharField(help_text='Caller-supplied or derived idempotency key.', max_length=255)),
                ('scope', models.CharField(help_text='Namespace for the key, e.g. "shopify.webhook.orders_create" or "api.orders.create", preventing collisions across unrelated operations that might reuse the same key value.', max_length=255)),
                ('request_hash', models.CharField(blank=True, help_text='SHA-256 hex digest of the normalized request payload, for conflict detection.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, help_text='HTTP-style status code of the cached result, if applicable.', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Small cached response returned to retrying callers. Never store secrets.', null=True)),
                ('expires_at', models.DateTimeField(help_text='When this key may be forgotten/reused. Cleanup is an external job.')),
            ],
            options={
                'verbose_name': 'Idempotency record',
                'verbose_name_plural': 'Idempotency records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='idempotency_by_expiry'), models.Index(fields=['status'], name='idempotency_by_status')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='unique_idempotency_key_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('source', models.CharField(help_text='System that delivered the event, e.g. "shopify", "stripe".', max_length=100)),
                ('external_event_id', models.CharField(help_text='Event identifier as assigned by the source system.', max_length=255)),
                ('event_type', models.CharField(help_text='Event type/topic as reported by the source, e.g. "orders/create".', max_length=150)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Small structured context about the event. Not the full raw payload.')),
            ],
            options={
                'verbose_name': 'Processed event',
                'verbose_name_plural': 'Processed events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'event_type'], name='proc_event_by_source_type'), models.Index(fields=['status'], name='proc_event_by_status'), models.Index(fields=['processed_at'], name='proc_event_by_processed_at')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_event_id'), name='unique_processed_event_per_source')],
            },
        ),
    ]
