# Generated by Django 6.1 on 2026-08-19 12:28

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('name', models.CharField(help_text='Market name, e.g. "United States" or "United States - West Coast".', max_length=150)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code, e.g. "US".', max_length=2)),
                ('region', models.CharField(blank=True, help_text='Optional sub-national/regional qualifier, e.g. "West Coast".', max_length=150)),
                ('currency', models.CharField(help_text='ISO 4217 currency code, e.g. "USD".', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether Ship is currently sourcing/evaluating opportunities in this market.')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country_code'], name='market_by_country_code'), models.Index(fields=['is_active'], name='market_by_is_active')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('country_code'), models.F('region'), name='market_analyst_market_unique_name_country_region')],
            },
        ),
        migrations.CreateModel(
            name='ProductOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('name', models.CharField(help_text='Product name or working title.', max_length=255)),
                ('category', models.CharField(help_text='Product category, e.g. "Jewelry".', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional free-text description of the product idea.')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('analyzing', 'Analyzing'), ('investigate', 'Investigate'), ('monitor', 'Monitor'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='discovered', help_text='Current lifecycle state of this opportunity.', max_length=20)),
                ('demand_score', models.DecimalField(blank=True, decimal_places=2, help_text='How strong current demand appears to be (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('trend_score', models.DecimalField(blank=True, decimal_places=2, help_text='How quickly demand is growing (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('margin_score', models.DecimalField(blank=True, decimal_places=2, help_text='How attractive potential margins appear to be (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('competition_score', models.DecimalField(blank=True, decimal_places=2, help_text='How competitive the market is; higher = less competition (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('saturation_score', models.DecimalField(blank=True, decimal_places=2, help_text='How saturated the product/category appears; higher = less saturated (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Composite opportunity score derived from the component scores above (0-100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('market', models.ForeignKey(help_text='Market this opportunity is being evaluated within.', on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='market_analyst.market')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this opportunity for analysis, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product opportunity',
                'verbose_name_plural': 'Product opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('summary', models.TextField(help_text='Human-readable summary of the analysis findings.')),
                ('recommendation', models.CharField(choices=[('strong_opportunity', 'Strong opportunity'), ('investigate', 'Investigate'), ('monitor', 'Monitor'), ('avoid', 'Avoid')], help_text='Bottom-line recommendation produced by this analysis.', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='How confident the analysis engine is in this result (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Structured, engine-specific evidence/breakdown backing this result. Schema-less; never trusted as-is.')),
                ('analysis_version', models.CharField(blank=True, help_text='Identifier of the analysis engine/schema version that produced this row, e.g. "heuristic-v1".', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Who/what produced this analysis, e.g. "market_analyst_agent" or an operator\'s identifier.', max_length=100)),
                ('opportunity', models.ForeignKey(help_text='Product opportunity this analysis result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='market_analyst.productopportunity')),
            ],
            options={
                'verbose_name': 'Market analysis',
                'verbose_name_plural': 'Market analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productopportunity',
            index=models.Index(fields=['market', 'status'], name='opportunity_by_market_status'),
        ),
        migrations.AddIndex(
            model_name='productopportunity',
            index=models.Index(fields=['status'], name='opportunity_by_status'),
        ),
        migrations.AddIndex(
            model_name='productopportunity',
            index=models.Index(fields=['overall_score'], name='opportunity_by_overall_score'),
        ),
        migrations.AddIndex(
            model_name='productopportunity',
            index=models.Index(fields=['category'], name='opportunity_by_category'),
        ),
        migrations.AddIndex(
            model_name='productopportunity',
            index=models.Index(fields=['created_at'], name='opportunity_by_created_at'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('demand_score__isnull', True), models.Q(('demand_score__gte', Decimal('0')), ('demand_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_demand_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('trend_score__isnull', True), models.Q(('trend_score__gte', Decimal('0')), ('trend_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_trend_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('margin_score__isnull', True), models.Q(('margin_score__gte', Decimal('0')), ('margin_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_margin_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('competition_score__isnull', True), models.Q(('competition_score__gte', Decimal('0')), ('competition_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_competition_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('saturation_score__isnull', True), models.Q(('saturation_score__gte', Decimal('0')), ('saturation_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_saturation_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('overall_score__isnull', True), models.Q(('overall_score__gte', Decimal('0')), ('overall_score__lte', Decimal('100'))), _connector='OR'), name='market_analyst_productopportunity_overall_score_in_range'),
        ),
        migrations.AddIndex(
            model_name='marketanalysis',
            index=models.Index(fields=['opportunity', '-created_at'], name='analysis_by_opp_created'),
        ),
        migrations.AddIndex(
            model_name='marketanalysis',
            index=models.Index(fields=['recommendation'], name='analysis_by_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='marketanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', Decimal('0')), ('confidence_score__lte', Decimal('100'))), name='market_analyst_marketanalysis_confidence_score_in_range'),
        ),
    ]
