# Generated by Django 6.1 on 2026-08-18 09:50

import apps.authentication.models
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('email', models.EmailField(help_text='Used as the login identifier. Must be unique (case-insensitive).', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting an account to deactivate it.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_staff'], name='user_active_staff_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='authentication_user_unique_lower_email')],
            },
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
    ]
