# Generated by Django 6.1 on 2026-08-19 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text="When the account's email address was confirmed via a SecurityToken. Null if unverified.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed login attempts since the last successful login. Policy-free counter.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='If set and in the future, authentication should be refused until this time.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the password was last changed. Used to invalidate sessions predating it.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this account may authenticate. Unselect to deactivate instead of deleting.'),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw refresh token. The raw value is never stored.', max_length=64, unique=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Shared across a login's full rotation chain, enabling revoke-on-reuse-detection.")),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('rotated', 'Rotated'), ('logout', 'Logout'), ('password_change', 'Password change'), ('user_revoked', 'Revoked by user'), ('admin_revoked', 'Revoked by administrator'), ('reuse_detected', 'Token reuse detected')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='reftoken_by_user_revoked'), models.Index(fields=['family_id'], name='reftoken_by_family'), models.Index(fields=['expires_at'], name='reftoken_by_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_reason', '')), models.Q(('revoked_at__isnull', False), models.Q(('revoked_reason', ''), _negated=True)), _connector='OR'), name='refreshtoken_revocation_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='SecurityToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique, non-sequential identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last saved (UTC). Not updated by QuerySet.update()/bulk_update() — see class docstring.')),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset')], max_length=32)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw token. The raw value is never stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was consumed. Null while still usable.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security token',
                'verbose_name_plural': 'security tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='sectoken_by_user_purpose'), models.Index(fields=['expires_at'], name='sectoken_by_expiry')],
            },
        ),
    ]
